name: fitness-tracker-prod
version: '3.8'

services:
  web:
    image: c.tsapp.dev/kanishka/fitness-tracker:latest  # Change to use local image
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8000"
    env_file:
      - .env.local_test
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=fitness_tracker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
    ports:
      - "5434:5432"

volumes:
  postgres_data: 