version: '3.8'

services:
  web:
    image: c.tsapp.dev/kanishka/fitness-tracker:latest
    env_file:
      - .env.prod
    environment:
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
    restart: unless-stopped
    expose:
      - 8000
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: nginx -g 'daemon off;'
    depends_on:
      - web
    networks:
      - app-network
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - app-network
    restart: unless-stopped
    ports:
      - "11434:11434"

networks:
  app-network:
    driver: bridge

volumes:
  ollama_data: