# Generated by Django 5.0 on 2024-12-28 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RawMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=50)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="WhatsAppUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_interaction", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProgressPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("media_id", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="whatsapp_bot.whatsappuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BodyHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "height",
                    models.FloatField(
                        blank=True, help_text="Height in centimeters", null=True
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        blank=True, help_text="Weight in kilograms", null=True
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("lose", "Lose Weight"),
                            ("maintain", "Maintain Weight"),
                            ("gain", "Gain Weight"),
                            ("muscle", "Build Muscle"),
                            ("strength", "Increase Strength"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "activity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sedentary", "Sedentary (little or no exercise)"),
                            ("light", "Lightly active (1-3 days/week)"),
                            ("moderate", "Moderately active (3-5 days/week)"),
                            ("very", "Very active (6-7 days/week)"),
                            ("extra", "Extra active (very active & physical job)"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("photo_link", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "dream_photo_link",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "body_fat",
                    models.FloatField(
                        blank=True,
                        help_text="Manually entered body fat percentage",
                        null=True,
                    ),
                ),
                (
                    "bmi",
                    models.FloatField(
                        blank=True, help_text="Body Mass Index", null=True
                    ),
                ),
                (
                    "maintenance_calories",
                    models.IntegerField(
                        blank=True, help_text="Daily maintenance calories", null=True
                    ),
                ),
                (
                    "body_composition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("calorie_deficit", "Calorie Deficit"),
                            ("body_recomposition", "Maintain Calorie"),
                            ("calorie_surplus", "Calorie Surplus"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="body_history",
                        to="whatsapp_bot.whatsappuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkoutSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("duration_minutes", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "raw_messages",
                    models.ManyToManyField(
                        related_name="workout_sessions", to="whatsapp_bot.rawmessage"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workouts",
                        to="whatsapp_bot.whatsappuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("weights", models.IntegerField()),
                ("sets", models.IntegerField()),
                ("reps", models.IntegerField()),
                (
                    "raw_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="whatsapp_bot.rawmessage",
                    ),
                ),
                (
                    "workout_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="whatsapp_bot.workoutsession",
                    ),
                ),
            ],
        ),
    ]
