# Generated by Django 5.0 on 2024-12-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp_bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawmessage",
            name="incoming",
            field=models.BooleanField(default=True),
        ),
    ]
