# Generated by Django 5.0 on 2024-12-28 12:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp_bot", "0002_rawmessage_incoming"),
    ]

    operations = [
        migrations.AddField(
            model_name="bodyhistory",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bodyhistory",
            name="activity",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="bodyhistory",
            name="bmi",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bodyhistory",
            name="body_composition",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="bodyhistory",
            name="body_fat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bodyhistory",
            name="dream_photo_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bodyhistory",
            name="goal",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="bodyhistory",
            name="height",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bodyhistory",
            name="maintenance_calories",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bodyhistory",
            name="photo_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bodyhistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="whatsapp_bot.whatsappuser",
            ),
        ),
        migrations.AlterField(
            model_name="bodyhistory",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
