# Generated by Django 5.0 on 2024-12-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "whatsapp_bot",
            "0003_bodyhistory_created_at_alter_bodyhistory_activity_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="weight_unit",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="exercise",
            name="workout_machine",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="bodyhistory",
            name="activity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sedentary", "Sedentary (little or no exercise)"),
                    ("light", "Lightly Active (1-3 days/week)"),
                    ("moderate", "Moderately Active (3-5 days/week)"),
                    ("very", "Very Active (6-7 days/week)"),
                    ("extra", "Extra Active (very active & physical job)"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bodyhistory",
            name="body_composition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("calorie_deficit", "Calorie Deficit"),
                    ("calorie_maintenance", "Calorie Maintenance"),
                    ("calorie_surplus", "Calorie Surplus"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bodyhistory",
            name="goal",
            field=models.CharField(
                blank=True,
                choices=[("lean", "Lean"), ("athletic", "Athletic"), ("bulk", "Bulk")],
                max_length=50,
                null=True,
            ),
        ),
    ]
