# Generated by Django 5.0 on 2024-12-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp_bot", "0004_exercise_weight_unit_exercise_workout_machine_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawmessage",
            name="processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workoutsession",
            name="processed_messages",
            field=models.ManyToManyField(
                related_name="processed_workout_sessions", to="whatsapp_bot.rawmessage"
            ),
        ),
        migrations.AlterField(
            model_name="workoutsession",
            name="raw_messages",
            field=models.ManyToManyField(
                related_name="raw_workout_sessions", to="whatsapp_bot.rawmessage"
            ),
        ),
    ]
