# Generated by Django 5.0 on 2024-12-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp_bot", "0006_whatsappuser_paid_paymenthistory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymenthistory",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "Payment histories",
            },
        ),
        migrations.RemoveField(
            model_name="paymenthistory",
            name="order_id",
        ),
        migrations.RemoveField(
            model_name="paymenthistory",
            name="payment_details",
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="currency",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="next_billing_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="payment_frequency_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="payment_frequency_interval",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Year", "Year"),
                    ("Month", "Month"),
                    ("Week", "Week"),
                    ("Day", "Day"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="product_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="quantity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="subscription_period_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="subscription_period_interval",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Year", "Year"),
                    ("Month", "Month"),
                    ("Week", "Week"),
                    ("Day", "Day"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="trial_period_days",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="paymenthistory",
            name="payment_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="paymenthistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("cancelled", "Cancelled"),
                    ("failed", "Failed"),
                ],
                max_length=20,
            ),
        ),
    ]
