# Generated by Django 5.0 on 2024-12-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp_bot", "0007_alter_paymenthistory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenthistory",
            name="type",
            field=models.CharField(default="test", max_length=255),
            preserve_default=False,
        ),
    ]
