# Generated by Django 5.0 on 2024-12-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp_bot", "0008_paymenthistory_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenthistory",
            name="business_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
