# Generated by Django 5.0 on 2024-12-30 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp_bot", "0009_paymenthistory_business_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="raw_message",
        ),
    ]
