# Generated by Django 5.0 on 2024-12-31 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp_bot", "0010_remove_exercise_raw_message"),
    ]

    operations = []
