# Generated by Django 5.0 on 2024-12-31 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp_bot", "0011_migrate_rawmessage_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawmessage",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="raw_messages",
                to="whatsapp_bot.whatsappuser",
            ),
        ),
        migrations.AlterField(
            model_name="bodyhistory",
            name="goal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("lean", "Lean (Slim and Defined)"),
                    ("athletic", "Athletic ( Muscular and Balanced)"),
                    ("bulk", "Bulk (Large and Powerful)"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
