# Generated by Django 5.0 on 2024-12-31 02:07

from django.db import migrations

def populate_users(apps, schema_editor):
    RawMessage = apps.get_model('whatsapp_bot', 'RawMessage')
    WhatsAppUser = apps.get_model('whatsapp_bot', 'WhatsAppUser')
    
    # Update all RawMessage records to link to their corresponding WhatsAppUser
    for message in RawMessage.objects.all():
        try:
            user = WhatsAppUser.objects.get(phone_number=message.phone_number)
            message.user = user
            message.save()
        except WhatsAppUser.DoesNotExist:
            # If no user exists with this phone number, create one
            user = WhatsAppUser.objects.create(phone_number=message.phone_number)
            message.user = user
            message.save()

def reverse_populate_users(apps, schema_editor):
    RawMessage = apps.get_model('whatsapp_bot', 'RawMessage')
    # Restore phone numbers from user relationship
    for message in RawMessage.objects.all():
        if message.user:
            message.phone_number = message.user.phone_number
            message.user = None
            message.save()

class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0012_add_nullable_user_to_rawmessage'),
    ]

    operations = [
        migrations.RunPython(populate_users, reverse_populate_users),
    ]
