# Generated by Django 5.0 on 2024-12-31 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp_bot", "0013_populate_rawmessage_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rawmessage",
            name="phone_number",
        ),
        migrations.AlterField(
            model_name="rawmessage",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="raw_messages",
                to="whatsapp_bot.whatsappuser",
            ),
            preserve_default=False,
        ),
    ]
