# Generated by Django 5.0 on 2024-12-31 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp_bot", "0014_remove_phone_number_from_rawmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="weight_unit",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
