# Generated by Django 5.0 on 2025-01-06 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp_bot", "0015_alter_exercise_weight_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="workoutsession",
            name="calories_burnt",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workoutsession",
            name="intensity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="DashboardDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("all_time_duration", models.IntegerField(blank=True, null=True)),
                ("last_week_duration", models.IntegerField(blank=True, null=True)),
                ("avg_week_duration", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("achievements", models.JSONField(blank=True, null=True)),
                ("initial_weight", models.FloatField(blank=True, null=True)),
                ("current_weight", models.FloatField(blank=True, null=True)),
                ("goal_weight", models.FloatField(blank=True, null=True)),
                ("fitness_score", models.IntegerField(blank=True, null=True)),
                ("fitness_score_change", models.IntegerField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_details",
                        to="whatsapp_bot.whatsappuser",
                    ),
                ),
            ],
        ),
    ]
