# Generated by Django 5.0 on 2025-01-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp_bot", "0016_workoutsession_calories_burnt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="muscle_group",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
